# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unitfile.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='unitfile.proto',
    package='ProtoFiles',
    syntax='proto3',
    serialized_pb=_b(
        '\n\x0eunitfile.proto\x12\nProtoFiles\"=\n\x07\x41\x63\x63\x44\x61ta\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\"\x9c\x01\n\x07LocData\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x10\n\x08latitude\x18\x02 \x01(\x02\x12\x11\n\tlongitude\x18\x03 \x01(\x02\x12\x10\n\x08\x61\x63\x63uracy\x18\x04 \x01(\x02\x12\r\n\x05speed\x18\x05 \x01(\x02\x12\x11\n\tdirection\x18\x06 \x01(\x08\x12%\n\x08\x61\x63\x63_data\x18\x07 \x03(\x0b\x32\x13.ProtoFiles.AccData\"\x82\x01\n\x08UnitFile\x12\x11\n\tdriver_id\x18\x01 \x01(\x04\x12\x12\n\nstart_time\x18\x02 \x01(\x01\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x01\x12%\n\x08loc_data\x18\x04 \x03(\x0b\x32\x13.ProtoFiles.LocData\x12\x16\n\x0etimezoneoffset\x18\x05 \x01(\x05\x42\x36\n*com.drivebuddyapp.drivebuddysdk.ProtoFilesB\x08ProtoBufb\x06proto3')
)

_ACCDATA = _descriptor.Descriptor(
    name='AccData',
    full_name='ProtoFiles.AccData',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='timestamp', full_name='ProtoFiles.AccData.timestamp', index=0,
            number=1, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='x', full_name='ProtoFiles.AccData.x', index=1,
            number=2, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='y', full_name='ProtoFiles.AccData.y', index=2,
            number=3, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='z', full_name='ProtoFiles.AccData.z', index=3,
            number=4, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=30,
    serialized_end=91,
)

_LOCDATA = _descriptor.Descriptor(
    name='LocData',
    full_name='ProtoFiles.LocData',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='timestamp', full_name='ProtoFiles.LocData.timestamp', index=0,
            number=1, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='latitude', full_name='ProtoFiles.LocData.latitude', index=1,
            number=2, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='longitude', full_name='ProtoFiles.LocData.longitude', index=2,
            number=3, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='accuracy', full_name='ProtoFiles.LocData.accuracy', index=3,
            number=4, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='speed', full_name='ProtoFiles.LocData.speed', index=4,
            number=5, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='direction', full_name='ProtoFiles.LocData.direction', index=5,
            number=6, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='acc_data', full_name='ProtoFiles.LocData.acc_data', index=6,
            number=7, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=94,
    serialized_end=250,
)

_UNITFILE = _descriptor.Descriptor(
    name='UnitFile',
    full_name='ProtoFiles.UnitFile',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='driver_id', full_name='ProtoFiles.UnitFile.driver_id', index=0,
            number=1, type=4, cpp_type=4, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='start_time', full_name='ProtoFiles.UnitFile.start_time', index=1,
            number=2, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='end_time', full_name='ProtoFiles.UnitFile.end_time', index=2,
            number=3, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='loc_data', full_name='ProtoFiles.UnitFile.loc_data', index=3,
            number=4, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='timezoneoffset', full_name='ProtoFiles.UnitFile.timezoneoffset', index=4,
            number=5, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=253,
    serialized_end=383,
)

_LOCDATA.fields_by_name['acc_data'].message_type = _ACCDATA
_UNITFILE.fields_by_name['loc_data'].message_type = _LOCDATA
DESCRIPTOR.message_types_by_name['AccData'] = _ACCDATA
DESCRIPTOR.message_types_by_name['LocData'] = _LOCDATA
DESCRIPTOR.message_types_by_name['UnitFile'] = _UNITFILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccData = _reflection.GeneratedProtocolMessageType('AccData', (_message.Message,), dict(
    DESCRIPTOR=_ACCDATA,
    __module__='unitfile_pb2'
    # @@protoc_insertion_point(class_scope:ProtoFiles.AccData)
))
_sym_db.RegisterMessage(AccData)

LocData = _reflection.GeneratedProtocolMessageType('LocData', (_message.Message,), dict(
    DESCRIPTOR=_LOCDATA,
    __module__='unitfile_pb2'
    # @@protoc_insertion_point(class_scope:ProtoFiles.LocData)
))
_sym_db.RegisterMessage(LocData)

UnitFile = _reflection.GeneratedProtocolMessageType('UnitFile', (_message.Message,), dict(
    DESCRIPTOR=_UNITFILE,
    __module__='unitfile_pb2'
    # @@protoc_insertion_point(class_scope:ProtoFiles.UnitFile)
))
_sym_db.RegisterMessage(UnitFile)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(),
                                                _b('\n*com.drivebuddyapp.drivebuddysdk.ProtoFilesB\010ProtoBuf'))
# @@protoc_insertion_point(module_scope)
